name: yshared_preferences
description: Flutter plugin for reading and writing simple key-value pairs.
  Wraps NSUserDefaults on iOS and SharedPreferences on Android.
version: 2.0.7

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.yzsharedpreferences
        pluginClass: SharedPreferencesPlugin
      ios:
        pluginClass: YZFLTSharedPreferencesPlugin

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  # The design on https://flutter.dev/go/federated-plugins was to leave
  # implementation constraints as "any". We cannot do it right now as it fails pub publish
  # validation, so we set a ^ constraint.
  # TODO(franciscojma): Revisit this (either update this part in the design or the pub tool).
  # https://github.com/flutter/flutter/issues/46264

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  pedantic: ^1.10.0
